#!/usr/bin/env bash
#Bash script that displays Best School 10 times, but the 9th iterate
name="Best School"
i=1
while [ $i -le 10 ]
do
	echo "$name"
	if [ $i -eq 9 ]
	then
		echo "Hi"
	fi
	((i++))
done
