#!/usr/bin/env bash
#bad luck from China,Japan,Italy for the 4th,9th,17th loop iteration
i=1
while [ "$i" -le 20 ]
do
	case "$i" in
		4)
			echo -e "$i"
			echo "bad luck from china";;
		9)
			echo -e "$i"
			echo "bad luck from Japan";;
		17)
			echo -e "$i"
			echo "bad luck from Italy";;
		*)
			echo -e "$i";;
	esac
	i=$((i+1))
done
