#!/usr/bin/env bash
#bad luck from China,Japan,Italy for the 4th,9th,17th loop iteration
i=1
while [ $i -le 20 ]
do
	echo "$i"
	case $i in
		"4") echo "bad luck from china";;
		"9") echo "bad luck from china";;
		"17") echo "bad luck from china";;
	esac
	((i++))
done
